[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
if G.SPLASH_LOGO then
    love.graphics.push()
    G.SPLASH_LOGO:translate_container()
    G.SPLASH_LOGO:draw()
    love.graphics.pop()
end
'''
position = "after"
payload = '''
if self.SPLASH_MKTJK_LOGO then
    love.graphics.push()
    self.SPLASH_MKTJK_LOGO.states.visible = mktjk.config.menu_logo
    self.SPLASH_MKTJK_LOGO:translate_container()
    self.SPLASH_MKTJK_LOGO:draw()
    self.SPLASH_MKTJK_LOGO.T.r = 0.08 * math.sin(G.TIMERS.REAL * 1.2)
    love.graphics.pop()
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
if self.SPLASH_LOGO then self.SPLASH_LOGO:remove(); self.SPLASH_LOGO = nil end
'''
position = "after"
payload = '''
if self.SPLASH_MKTJK_LOGO then self.SPLASH_MKTJK_LOGO:remove(); self.SPLASH_MKTJK_LOGO = nil end
'''
match_indent = true
times = 1